version: "3"
services:
  nodeserver:
    restart: always
    build:
      context: ./app
    ports:
      - "86:5001"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "99:80"
